/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ShardVersion {
  shardId: number
  version: string
  segmentIds: Array<string>
}
export interface SearchResult {
  docId: number
  score: number
  highlights?: Record<string, Array<Array<number>>>
  fields?: Record<string, string>
}
export interface FieldDef {
  name: string
  type: 'text' | 'string' | 'u64' | 'i64' | 'f64'
  stored?: boolean
  indexed?: boolean
  fast?: boolean
}
export interface SearchOptions {
  limit?: number
  highlights?: boolean
  allowedIds?: Array<number>
  fields?: boolean
}
/**
 * Merge BM25 stats from multiple nodes into global stats (for distributed search).
 *
 * Each node calls `index.exportStats(queryJson)` which returns a JSON string.
 * The coordinator collects all JSON strings and merges them with this function.
 * The merged result is then passed back to each node via
 * `index.searchWithGlobalStats(queryJson, mergedJson)`.
 *
 * @param statsList - Array of JSON strings, one per node (from `exportStats()`).
 * @returns JSON string of merged `ExportableStats` ready for `searchWithGlobalStats()`.
 */
export declare function mergeStats(statsList: Array<string>): string
/**
 * The object a JavaScript program hands to `BlobIndex.create()` /
 * `BlobIndex.open()`. Methods are called with the object as `this`. Each may
 * return its value directly or a Promise of it.
 *
 * Keys: `indexName` is `"Lucivy_<name>/shard_<i>"` for segment files and the
 * bare `<name>` for the root files (`_shard_config.json`, `_shard_stats.bin`);
 * `fileName` is the file within that namespace.
 */
export interface BlobStoreCallbacks {
  /** Bytes of a blob, or `null` when it does not exist. */
  load: (indexName: string, fileName: string) => Buffer | Uint8Array | null | Promise<Buffer | Uint8Array | null>
  /** Create or overwrite a blob. */
  save: (indexName: string, fileName: string, data: Buffer) => void | Promise<void>
  /** Remove a blob; a missing blob is not an error. */
  delete: (indexName: string, fileName: string) => void | Promise<void>
  exists: (indexName: string, fileName: string) => boolean | Promise<boolean>
  /** Every file name stored under `indexName`. */
  list: (indexName: string) => string[] | Promise<string[]>
  /**
   * Optional, for `lazy: true`: size of a blob without loading it
   * (`null` = unknown, the file is then loaded whole on first open).
   */
  blobLen?: (indexName: string, fileName: string) => number | null | Promise<number | null>
  /**
   * Optional, for `lazy: true`: `length` bytes of a blob from `offset`
   * (`null` = unsupported, the file is then loaded whole).
   */
  loadRange?: (indexName: string, fileName: string, offset: number, length: number) => Buffer | Uint8Array | null | Promise<Buffer | Uint8Array | null>
}
/** Options of `BlobIndex.create()` / `BlobIndex.open()`. */
export interface BlobIndexOptions {
  /**
   * Local directory for the mmap cache of the blobs (default: `lucivy_blob_cache`
   * under the OS temp dir). Disposable: the store is the source of truth.
   */
  cacheDir?: string
  /**
   * Pull blobs on first use instead of all at open. Needs `blobLen` and
   * `loadRange` on the store to be worth it.
   */
  lazy?: boolean
  /** `create()` only: number of shards (default 1). */
  shards?: number
}
export declare class Index {
  /**
   * Create a new index at the given path.
   *
   * @param path - Directory path for the index files.
   * @param fields - Field definitions: `[{name: "body", type: "text", stored: true}]`.
   *   Types: `"text"` (full-text), `"u64"`, `"i64"`, `"f64"`, `"bool"`, `"date"`.
   * @param shards - Number of shards (default 1). More shards = faster search on large datasets.
   */
  static create(path: string, fields: Array<FieldDef>, shards?: number | undefined | null): Index
  /**
   * Open an existing index at the given path.
   *
   * Reads the persisted schema and segment metadata from disk.
   * The index must have been previously created with `Index.create()`.
   *
   * @param path - Directory path of the existing index (same path used in `create()`).
   * @returns An `Index` ready for search, add, delete, etc.
   */
  static open(path: string): Index
  /**
   * Add a document.
   *
   * @param docId - Unique document ID (_node_id).
   * @param fields - Object with field names as keys: `{title: "Hello", body: "World", score: 3.14}`
   */
  add(docId: number, fields: Record<string, any>): void
  /**
   * Add multiple documents at once.
   *
   * Each element must have a `docId` (or `doc_id`) key plus field values.
   *
   * @param docs - Array of objects: `[{docId: 1, title: "Hello"}, {docId: 2, title: "World"}]`.
   */
  addMany(docs: Array<Record<string, any>>): void
  /**
   * Delete a document by its `_node_id`.
   *
   * The deletion is staged in memory. Call `commit()` or run a search
   * (which auto-commits via lazy commit) to make it visible.
   *
   * @param docId - The `_node_id` of the document to delete.
   */
  delete(docId: number): void
  /**
   * Update a document (delete old + re-add with new fields).
   *
   * @param docId - The `_node_id` of the document to update.
   * @param fields - New field values: `{title: "Updated", body: "New content"}`.
   */
  update(docId: number, fields: Record<string, any>): void
  /**
   * Commit pending changes to disk, making them visible to subsequent searches.
   *
   * Lucivy uses lazy commit: if you search without calling `commit()`,
   * uncommitted changes are auto-flushed before the search executes.
   * Call `commit()` explicitly when you need to control the commit point
   * (e.g., after a batch of adds/deletes).
   */
  commit(): void
  /**
   * Flush any pending writes and release the writer lock.
   *
   * After `close()`, the index data remains on disk and can be re-opened
   * with `Index.open()`. No further mutations are allowed on this instance.
   *
   * On a snapshot served with `openSnapshot()` there is nothing to flush
   * and no lock to release: `close()` is a no-op.
   */
  close(): void
  /**
   * Search the index.
   *
   * @param query - String or query object.
   *
   * **String**: `"hello world"` — auto contains_split across all text fields.
   *
   * **Query object** (all substring queries are cross-token):
   * - `{type: "contains", field: "body", value: "lock"}` — substring match
   * - `{type: "contains", field: "body", value: "lock", distance: 1}` — fuzzy substring
   * - `{type: "contains", field: "body", value: "lock.*init", regex: true}` — regex substring
   * - `{type: "startsWith", field: "body", value: "lock"}` — token prefix
   * - `{type: "contains_split", field: "body", value: "struct device"}` — words OR'd
   * - `{type: "term", field: "body", value: "lock"}` — exact whole-token
   * - `{type: "fuzzy", field: "body", value: "schdule", distance: 1}` — alias for contains+distance
   * - `{type: "phrase", field: "body", value: "mutex lock"}` — adjacent tokens
   * - `{type: "regex", field: "body", pattern: "sched[a-z]+"}` — regex on tokens
   * - `{type: "boolean", must: [...], should: [...], must_not: [...]}` — boolean combo
   * - `{type: "disjunction_max", queries: [...], tie_breaker: 0.1}` — best score
   * - `{type: "more_like_this", field: "body", value: "sample text", min_doc_frequency: 1}` — similarity
   *
   * **Filtering:**
   * - `allowedIds` in options: pre-filter by _node_id (fast, bitmap-based)
   * - `filters` key in query: filter on non-text fields (AND'd with search):
   *   ```json
   *   {type: "contains", field: "body", value: "lock",
   *    filters: [
   *      {field: "category", op: "eq", value: "kernel"},
   *      {field: "score", op: "gte", value: 0.5},
   *      {field: "status", op: "in", value: ["active", "review"]}
   *    ]}
   *   ```
   *   Ops: `eq`, `ne`, `lt`, `lte`, `gt`, `gte`, `in`, `not_in`, `between`, `starts_with`, `contains`.
   *   Composite: `must`, `should`, `must_not` with nested `clauses`.
   *
   * Honest warnings for a query, without running it.
   *
   * Plain-text warnings describing what the engine will actually search
   * and where it falls back to brute force: separators ignored in relaxed
   * mode, fuzzy distance too loose for the query length, regex without a
   * usable literal (full scan), segments written by the legacy indexer.
   * Empty array when nothing applies.
   */
  queryWarnings(query: any): Array<string>
  /** @param options - `{limit?: number, highlights?: boolean, fields?: boolean, allowedIds?: number[]}` */
  search(query: any, options?: SearchOptions | undefined | null): Array<SearchResult>
  /**
   * Number of documents in the index (getter, access as `index.numDocs`).
   *
   * @returns Total document count across all shards.
   */
  get numDocs(): number
  /**
   * Number of shards (getter, access as `index.numShards`).
   *
   * @returns Shard count (1 for single-shard indexes).
   */
  get numShards(): number
  /**
   * Index directory path (getter, access as `index.path`).
   *
   * @returns The directory path where the index files are stored.
   */
  get path(): string
  /**
   * Export this index as a LUCE snapshot.
   *
   * Returns the full index content (all shards, schema, segments) as a
   * binary blob. Restore later with `Index.importSnapshot()`.
   *
   * @returns `Buffer` containing the LUCE snapshot bytes.
   */
  exportSnapshot(): Buffer
  /**
   * Export this index as a LUCE snapshot directly to a file.
   *
   * @param path - Destination file path (typically ending in `.luce`).
   */
  exportSnapshotTo(path: string): void
  /**
   * Import an index from a LUCE snapshot (Buffer).
   *
   * Restores a full index from a binary blob previously created by
   * `exportSnapshot()`. The index files are written to `destPath`.
   *
   * @param data - Raw LUCE snapshot bytes (Buffer).
   * @param destPath - Directory to write the restored index into.
   *   Defaults to `"/tmp/lucivy_import"`.
   * @returns A new `Index` instance ready for search.
   */
  static importSnapshot(data: Buffer, destPath?: string | undefined | null): Index
  /**
   * Import an index from a LUCE snapshot file (.luce).
   *
   * Convenience wrapper that reads the file then calls `importSnapshot()`.
   *
   * @param path - Path to the `.luce` snapshot file.
   * @param destPath - Directory to write the restored index into.
   *   Defaults to `"/tmp/lucivy_import"`.
   * @returns A new `Index` instance ready for search.
   */
  static importSnapshotFrom(path: string, destPath?: string | undefined | null): Index
  /**
   * Serve a LUCE snapshot (Buffer) directly, without extracting it.
   *
   * The blob itself is the index: readers get slices of it, nothing is
   * written to disk and the memory cost is the blob's own length. The
   * result is **read-only** — `add()`, `delete()`, `commit()`, `compact()`
   * and the delta/snapshot exports fail with a clear error. To get a
   * writable index back, use `Index.importSnapshot()` instead.
   *
   * @param data - Raw LUCE snapshot bytes (Buffer), as produced by `exportSnapshot()`.
   * @returns A read-only `Index` ready for search. Its `path` is `""`.
   */
  static openSnapshot(data: Buffer): Index
  /**
   * Serve a LUCE snapshot file (.luce) directly, without extracting it.
   *
   * Convenience wrapper that reads the file then calls `openSnapshot()`.
   * Same read-only semantics.
   *
   * @param path - Path to the `.luce` snapshot file.
   * @returns A read-only `Index` ready for search.
   */
  static openSnapshotFrom(path: string): Index
  /**
   * Merge every shard's segments into segments of at most `maxDocs`
   * documents, then commit.
   *
   * Bulk loading leaves many small segments behind; one `compact()` after
   * the load makes searches faster and the index smaller on disk. Not
   * something to call on every commit.
   *
   * @param maxDocs - Upper bound on documents per merged segment (default 10000).
   * @returns Number of merge rounds that actually reduced a shard's segment count.
   */
  compact(maxDocs?: number | undefined | null): number
  /**
   * Block until no background merge is running or about to start.
   *
   * Segment merges run in the background after commits. Call this before
   * anything that needs a stable set of files or the full address space —
   * measuring `indexBytes()`, copying the directory, exporting a snapshot
   * under memory pressure.
   *
   * @returns Number of rounds that still saw merge activity (0 = already quiet).
   */
  waitMergesQuiet(): number
  /**
   * On-disk bytes of every searchable segment of every shard.
   *
   * Sums the segment files; the number moves while merges run, so call
   * `waitMergesQuiet()` first for a stable figure.
   *
   * @returns Total size in bytes (a `number`; exact below 2^53).
   */
  indexBytes(): number
  /**
   * True when the last search hit the per-segment match cap
   * (`LUCIVY_MAX_MATCHES_PER_SEGMENT`, `0` disables it) on some segment:
   * the hits are real, but some documents were never looked at.
   */
  lastSearchTruncated(): boolean
  /**
   * Delete the whole index: commit and release everything (like `close()`),
   * then remove the index files from disk.
   *
   * This consumes the underlying handle. After `dropIndex()` every other
   * method on this instance throws; create or open a new `Index` instead.
   */
  dropIndex(): void
  /**
   * Schema as a list of field definitions (getter, access as `index.schema`).
   *
   * @returns `Array<{name: string, type: string}>` for each user-defined field.
   */
  get schema(): Array<FieldDef>
  /**
   * Per-shard version info for delta sync (getter, access as `index.shardVersions`).
   *
   * Returns the current version and segment IDs for each shard.
   * Pass this to a remote server's `exportShardedDelta()` to
   * receive only the segments that changed since your last sync.
   *
   * @returns `Array<{shardId: number, version: string, segmentIds: string[]}>`.
   */
  get shardVersions(): Array<ShardVersion>
  /**
   * Export a sharded delta (LUCIDS blob) containing only segments that
   * changed since the client's known versions.
   *
   * Used for incremental sync: the client sends its `shardVersions`,
   * the server computes and returns only the diff.
   *
   * @param clientVersions - Array of `{shardId, version, segmentIds}`,
   *   typically obtained from the client's `shardVersions` getter.
   * @returns `Buffer` containing the LUCIDS binary delta blob.
   */
  exportShardedDelta(clientVersions: Array<ShardVersion>): Buffer
  /**
   * Apply a sharded delta (LUCIDS blob) to this index.
   *
   * Merges the delta's segments into the local index, bringing it
   * up to date with the server. Only modified shards are touched.
   *
   * @param data - LUCIDS binary blob from `exportShardedDelta()`.
   */
  applyShardedDelta(data: Buffer): void
  /**
   * Export BM25 statistics for a query (for distributed search).
   *
   * In a distributed setup, each node exports its local BM25 stats.
   * A coordinator merges them into global stats and sends them back
   * for scoring with `searchWithGlobalStats()`.
   *
   * @param queryJson - JSON string of QueryConfig (same format as `search()` object).
   * @returns JSON string of `ExportableStats` (document frequencies, doc counts).
   */
  exportStats(queryJson: string): string
  /**
   * Search using externally-provided global BM25 stats (distributed mode).
   *
   * Scores are computed using the merged global stats instead of local-only
   * stats, ensuring consistent ranking across nodes.
   *
   * @param queryJson - JSON string of QueryConfig.
   * @param globalStatsJson - JSON string of merged `ExportableStats`
   *   from all nodes (obtained by merging `exportStats()` outputs).
   * @param limit - Maximum number of results (default 10).
   * @param highlights - If true, return highlight byte offsets per field.
   * @param allowedIds - Restrict the search to those `_node_id` values: a
   *   real pre-filter, under the federation's statistics — the ids decide
   *   which documents are visited, the statistics how they score.
   * @returns `Array<SearchResult>` scored with global BM25 statistics.
   */
  searchWithGlobalStats(queryJson: string, globalStatsJson: string, limit?: number | undefined | null, highlights?: boolean | undefined | null, allowedIds?: Array<number> | undefined | null): Array<SearchResult>
}
/**
 * An index whose files live in a storage you provide — a transactional
 * database, an object store, a Map — through the `BlobStoreCallbacks`
 * object. Every method returns a Promise: the work runs off the JS thread,
 * which stays free to serve the store callbacks.
 */
export declare class BlobIndex {
  /**
   * Create a new index in the given store.
   *
   * @param store - Object implementing the store protocol (`load`, `save`, `delete`, `exists`, `list`, optional `blobLen` / `loadRange`).
   * @param indexName - Name of the index inside the store.
   * @param fields - Field definitions, as for `Index.create()`.
   * @param options - `{cacheDir?, lazy?, shards?}`.
   */
  static create(store: BlobStoreCallbacks, indexName: string, fields: Array<FieldDef>, options?: BlobIndexOptions | undefined | null): Promise<BlobIndex>
  /**
   * Open an index that already exists in the store.
   *
   * @param store - Same protocol as for `create()`.
   * @param indexName - Name given at creation.
   * @param options - `{cacheDir?, lazy?}`.
   */
  static open(store: BlobStoreCallbacks, indexName: string, options?: BlobIndexOptions | undefined | null): Promise<BlobIndex>
  /** Add a document. Same arguments as `Index.add()`. */
  add(docId: number, fields: Record<string, any>): Promise<void>
  /** Add multiple documents. Same arguments as `Index.addMany()`. */
  addMany(docs: Array<Record<string, any>>): Promise<void>
  /** Delete a document by its `_node_id` (staged until `commit()`). */
  delete(docId: number): Promise<void>
  /** Update a document (delete old + re-add with new fields). */
  update(docId: number, fields: Record<string, any>): Promise<void>
  /**
   * Commit pending changes to the store: segment files are saved through
   * `store.save()`, `meta.json` last (the commit point).
   */
  commit(): Promise<void>
  /** Search. Same arguments and results as `Index.search()`. */
  search(query: any, options?: SearchOptions | undefined | null): Promise<Array<SearchResult>>
  /** Honest warnings for a query, without running it. See `Index.queryWarnings()`. */
  queryWarnings(query: any): Promise<Array<string>>
  /** Number of documents across all shards. */
  numDocs(): Promise<number>
  /**
   * Flush pending writes, wait for merges, release the writer lock.
   * After `close()` the store is not touched again: it is safe to tear
   * down whatever backs it. Always call it before the process exits.
   */
  close(): Promise<void>
  /**
   * Merge every shard's segments into segments of at most `maxDocs`
   * documents, then commit. See `Index.compact()`.
   */
  compact(maxDocs?: number | undefined | null): Promise<number>
  /** Block until no background merge is running or about to start. */
  waitMergesQuiet(): Promise<number>
  /** Bytes of every searchable segment of every shard, as cached locally. */
  indexBytes(): Promise<number>
  /**
   * Delete the whole index: `close()`, then every blob the store holds
   * for it — the `Lucivy_<name>/shard_<i>` namespaces and the root
   * `<name>` namespace, each listed with `store.list()` and removed with
   * `store.delete()`. Consumes the handle: every later call throws.
   */
  dropIndex(): Promise<void>
  /** Name of the index inside the store (getter). */
  get indexName(): string
  /** Number of shards (getter). */
  get numShards(): number
  /** Schema as a list of field definitions (getter). */
  get schema(): Array<FieldDef>
}
