/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ShardVersion {
  shardId: number
  version: string
  segmentIds: Array<string>
}
export interface SearchResult {
  docId: number
  score: number
  highlights?: Record<string, Array<Array<number>>>
  fields?: Record<string, string>
}
export interface FieldDef {
  name: string
  type: 'text' | 'string' | 'u64' | 'i64' | 'f64'
  stored?: boolean
  indexed?: boolean
  fast?: boolean
}
export interface SearchOptions {
  limit?: number
  highlights?: boolean
  allowedIds?: Array<number>
  fields?: boolean
}
/**
 * Merge BM25 stats from multiple nodes into global stats (for distributed search).
 *
 * @param statsList - Array of JSON strings, one per node (from `exportStats()`).
 * @returns JSON string of merged `ExportableStats` ready for `searchWithGlobalStats()`.
 */
export declare function mergeStats(statsList: Array<string>): string

export declare class Index {
  /**
   * Create a new index at the given path.
   *
   * @param path - Directory path for the index files.
   * @param fields - Field definitions: `[{name: "body", type: "text", stored: true}]`.
   *   Types: `"text"` (full-text), `"u64"`, `"i64"`, `"f64"`, `"bool"`, `"date"`.
   * @param shards - Number of shards (default 1). More shards = faster search on large datasets.
   */
  static create(path: string, fields: Array<FieldDef>, shards?: number | undefined | null): Index
  /**
   * Open an existing index at the given path.
   *
   * Reads the persisted schema and segment metadata from disk.
   * The index must have been previously created with `Index.create()`.
   *
   * @param path - Directory path of the existing index (same path used in `create()`).
   * @returns An `Index` ready for search, add, delete, etc.
   */
  static open(path: string): Index
  /**
   * Add a document.
   *
   * @param docId - Unique document ID (_node_id).
   * @param fields - Object with field names as keys: `{title: "Hello", body: "World", score: 3.14}`
   */
  add(docId: number, fields: Record<string, any>): void
  /**
   * Add multiple documents at once.
   *
   * Each element must have a `docId` (or `doc_id`) key plus field values.
   *
   * @param docs - Array of objects: `[{docId: 1, title: "Hello"}, {docId: 2, title: "World"}]`.
   */
  addMany(docs: Array<Record<string, any>>): void
  /**
   * Delete a document by its `_node_id`.
   *
   * The deletion is staged in memory. Call `commit()` or run a search
   * (which auto-commits via lazy commit) to make it visible.
   *
   * @param docId - The `_node_id` of the document to delete.
   */
  delete(docId: number): void
  /**
   * Update a document (delete old + re-add with new fields).
   *
   * @param docId - The `_node_id` of the document to update.
   * @param fields - New field values: `{title: "Updated", body: "New content"}`.
   */
  update(docId: number, fields: Record<string, any>): void
  /**
   * Commit pending changes to disk, making them visible to subsequent searches.
   *
   * Lucivy uses lazy commit: if you search without calling `commit()`,
   * uncommitted changes are auto-flushed before the search executes.
   * Call `commit()` explicitly when you need to control the commit point
   * (e.g., after a batch of adds/deletes).
   */
  commit(): void
  /**
   * Flush any pending writes and release the writer lock.
   *
   * After `close()`, the index data remains on disk and can be re-opened
   * with `Index.open()`. No further mutations are allowed on this instance.
   */
  close(): void
  /**
   * Search the index.
   *
   * @param query - String or query object.
   *
   * **String**: `"hello world"` — auto contains_split across all text fields.
   *
   * **Query object** (all substring queries are cross-token):
   * - `{type: "contains", field: "body", value: "lock"}` — substring match
   * - `{type: "contains", field: "body", value: "lock", distance: 1}` — fuzzy substring
   * - `{type: "contains", field: "body", value: "lock.*init", regex: true}` — regex substring
   * - `{type: "startsWith", field: "body", value: "lock"}` — token prefix
   * - `{type: "contains_split", field: "body", value: "struct device"}` — words OR'd
   * - `{type: "term", field: "body", value: "lock"}` — exact whole-token
   * - `{type: "fuzzy", field: "body", value: "schdule", distance: 1}` — alias for contains+distance
   * - `{type: "phrase", field: "body", value: "mutex lock"}` — adjacent tokens
   * - `{type: "regex", field: "body", pattern: "sched[a-z]+"}` — regex on tokens
   * - `{type: "boolean", must: [...], should: [...], must_not: [...]}` — boolean combo
   * - `{type: "disjunction_max", queries: [...], tie_breaker: 0.1}` — best score
   * - `{type: "more_like_this", field: "body", value: "sample text", min_doc_frequency: 1}` — similarity
   *
   * **Filtering:**
   * - `allowed_ids` in options: pre-filter by _node_id (fast, bitmap-based)
   * - `filters` key in query: filter on non-text fields (AND'd with search):
   *   ```json
   *   {type: "contains", field: "body", value: "lock",
   *    filters: [
   *      {field: "category", op: "eq", value: "kernel"},
   *      {field: "score", op: "gte", value: 0.5},
   *      {field: "status", op: "in", value: ["active", "review"]}
   *    ]}
   *   ```
   *   Ops: `eq`, `ne`, `lt`, `lte`, `gt`, `gte`, `in`, `not_in`, `between`, `starts_with`, `contains`.
   *   Composite: `must`, `should`, `must_not` with nested `clauses`.
   *
   * @param options - `{limit?: number, highlights?: boolean, fields?: boolean, allowed_ids?: number[]}`
   */
  search(query: any, options?: SearchOptions | undefined | null): Array<SearchResult>
  /**
   * Number of documents in the index (getter, access as `index.numDocs`).
   *
   * @returns Total document count across all shards.
   */
  get numDocs(): number
  /**
   * Number of shards (getter, access as `index.numShards`).
   *
   * @returns Shard count (1 for single-shard indexes).
   */
  get numShards(): number
  /**
   * Index directory path (getter, access as `index.path`).
   *
   * @returns The directory path where the index files are stored.
   */
  get path(): string
  /**
   * Export this index as a LUCE snapshot.
   *
   * Returns the full index content (all shards, schema, segments) as a
   * binary blob. Restore later with `Index.importSnapshot()`.
   *
   * @returns `Buffer` containing the LUCE snapshot bytes.
   */
  exportSnapshot(): Buffer
  /**
   * Export this index as a LUCE snapshot directly to a file.
   *
   * @param path - Destination file path (typically ending in `.luce`).
   */
  exportSnapshotTo(path: string): void
  /**
   * Import an index from a LUCE snapshot (Buffer).
   *
   * Restores a full index from a binary blob previously created by
   * `exportSnapshot()`. The index files are written to `destPath`.
   *
   * @param data - Raw LUCE snapshot bytes (Buffer).
   * @param destPath - Directory to write the restored index into.
   *   Defaults to `"/tmp/lucivy_import"`.
   * @returns A new `Index` instance ready for search.
   */
  static importSnapshot(data: Buffer, destPath?: string | undefined | null): Index
  /**
   * Import an index from a LUCE snapshot file (.luce).
   *
   * Convenience wrapper that reads the file then calls `importSnapshot()`.
   *
   * @param path - Path to the `.luce` snapshot file.
   * @param destPath - Directory to write the restored index into.
   *   Defaults to `"/tmp/lucivy_import"`.
   * @returns A new `Index` instance ready for search.
   */
  static importSnapshotFrom(path: string, destPath?: string | undefined | null): Index
  /**
   * Schema as a list of field definitions (getter, access as `index.schema`).
   *
   * @returns `Array<{name: string, type: string}>` for each user-defined field.
   */
  get schema(): Array<FieldDef>
  /**
   * Per-shard version info for delta sync (getter, access as `index.shardVersions`).
   *
   * Returns the current version and segment IDs for each shard.
   * Pass this to a remote server's `exportShardedDelta()` to
   * receive only the segments that changed since your last sync.
   *
   * @returns `Array<{shardId: number, version: string, segmentIds: string[]}>`.
   */
  get shardVersions(): Array<ShardVersion>
  /**
   * Export a sharded delta (LUCIDS blob) containing only segments that
   * changed since the client's known versions.
   *
   * Used for incremental sync: the client sends its `shardVersions`,
   * the server computes and returns only the diff.
   *
   * @param clientVersions - Array of `{shardId, version, segmentIds}`,
   *   typically obtained from the client's `shardVersions` getter.
   * @returns `Buffer` containing the LUCIDS binary delta blob.
   */
  exportShardedDelta(clientVersions: Array<ShardVersion>): Buffer
  /**
   * Apply a sharded delta (LUCIDS blob) to this index.
   *
   * Merges the delta's segments into the local index, bringing it
   * up to date with the server. Only modified shards are touched.
   *
   * @param data - LUCIDS binary blob from `exportShardedDelta()`.
   */
  applyShardedDelta(data: Buffer): void
  /**
   * Export BM25 statistics for a query (for distributed search).
   *
   * In a distributed setup, each node exports its local BM25 stats.
   * A coordinator merges them into global stats and sends them back
   * for scoring with `searchWithGlobalStats()`.
   *
   * @param queryJson - JSON string of QueryConfig (same format as `search()` object).
   * @returns JSON string of `ExportableStats` (document frequencies, doc counts).
   */
  exportStats(queryJson: string): string
  /**
   * Search using externally-provided global BM25 stats (distributed mode).
   *
   * Scores are computed using the merged global stats instead of local-only
   * stats, ensuring consistent ranking across nodes.
   *
   * @param queryJson - JSON string of QueryConfig.
   * @param globalStatsJson - JSON string of merged `ExportableStats`
   *   from all nodes (obtained by merging `exportStats()` outputs).
   * @param limit - Maximum number of results (default 10).
   * @param highlights - If true, return highlight byte offsets per field.
   * @returns `Array<SearchResult>` scored with global BM25 statistics.
   */
  searchWithGlobalStats(queryJson: string, globalStatsJson: string, limit?: number | undefined | null, highlights?: boolean | undefined | null): Array<SearchResult>
}
